//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassionProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listings2
    {
        public int ID { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> Accomodates { get; set; }
        public string Bathroom { get; set; }
        public string Location { get; set; }
        public string imagePath { get; set; }
    }
}
